"""empty message

Revision ID: 0fb76a5bfe67
Revises: 36916c090daf
Create Date: 2021-05-23 12:55:04.338828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb76a5bfe67'
down_revision = '36916c090daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejerciciosxbloque', sa.Column('num_ejercicio', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ejerciciosxbloque', 'num_ejercicio')
    # ### end Alembic commands ###
