"""empty message

Revision ID: 1fc6a2db2df1
Revises: 
Create Date: 2021-01-23 17:52:05.113184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fc6a2db2df1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_mesociclo',
    sa.Column('id_estado_mesociclo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_estado_mesociclo'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('id_estado_mesociclo')
    )
    op.create_table('generos',
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_genero'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('id_genero')
    )
    op.create_table('niveles',
    sa.Column('id_nivel', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_nivel'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('id_nivel')
    )
    op.create_table('objetivos',
    sa.Column('id_objetivo', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_objetivo'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('id_objetivo')
    )
    op.create_table('organizaciones',
    sa.Column('id_organizacion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_organizacion'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('id_organizacion')
    )
    op.create_table('patrones_movimiento',
    sa.Column('id_patron_movimiento', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_patron_movimiento'),
    sa.UniqueConstraint('id_patron_movimiento')
    )
    op.create_table('ejercicios',
    sa.Column('id_ejercicio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('id_patron', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_patron'], ['patrones_movimiento.id_patron_movimiento'], ),
    sa.PrimaryKeyConstraint('id_ejercicio'),
    sa.UniqueConstraint('id_ejercicio')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=250), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('img_url', sa.String(length=250), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('id_genero', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('id_nivel', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_genero'], ['generos.id_genero'], ),
    sa.ForeignKeyConstraint(['id_nivel'], ['niveles.id_nivel'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('apellido'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('img_url'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('mesociclos',
    sa.Column('id_mesociclo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_nivel', sa.Integer(), nullable=True),
    sa.Column('id_estado', sa.Integer(), nullable=True),
    sa.Column('id_objetivo', sa.Integer(), nullable=True),
    sa.Column('id_organizacion', sa.Integer(), nullable=True),
    sa.Column('id_principal_tren_superior', sa.Integer(), nullable=True),
    sa.Column('id_principal_tren_inferior', sa.Integer(), nullable=True),
    sa.Column('semanas_por_mesociclo', sa.Integer(), nullable=False),
    sa.Column('sesiones_por_semana', sa.Integer(), nullable=False),
    sa.Column('fecha_fin_real', sa.DateTime(), nullable=True),
    sa.Column('aumento_motivacion', sa.Boolean(), nullable=True),
    sa.Column('mas_cerca_objetivos', sa.Boolean(), nullable=True),
    sa.Column('sentimiento', sa.Integer(), nullable=True),
    sa.Column('durmiendo', sa.Integer(), nullable=True),
    sa.Column('alimentado', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_estado'], ['estados_mesociclo.id_estado_mesociclo'], ),
    sa.ForeignKeyConstraint(['id_nivel'], ['niveles.id_nivel'], ),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivos.id_objetivo'], ),
    sa.ForeignKeyConstraint(['id_organizacion'], ['organizaciones.id_organizacion'], ),
    sa.ForeignKeyConstraint(['id_principal_tren_inferior'], ['ejercicios.id_ejercicio'], ),
    sa.ForeignKeyConstraint(['id_principal_tren_superior'], ['ejercicios.id_ejercicio'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mesociclo'),
    sa.UniqueConstraint('id_mesociclo')
    )
    op.create_table('sesiones',
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_mesociclo', sa.Integer(), nullable=True),
    sa.Column('fecha_empezado', sa.DateTime(), nullable=True),
    sa.Column('fecha_finalizado', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mesociclo'], ['mesociclos.id_mesociclo'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_sesion'),
    sa.UniqueConstraint('id_sesion')
    )
    op.create_table('bloques',
    sa.Column('id_bloque', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('num_bloque', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesiones.id_sesion'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_bloque'),
    sa.UniqueConstraint('id_bloque')
    )
    op.create_table('ejerciciosxbloque',
    sa.Column('id_ejerciciosxbloque', sa.Integer(), nullable=False),
    sa.Column('id_ejercicio', sa.Integer(), nullable=True),
    sa.Column('id_bloque', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('carga', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_bloque'], ['bloques.id_bloque'], ),
    sa.ForeignKeyConstraint(['id_ejercicio'], ['ejercicios.id_ejercicio'], ),
    sa.PrimaryKeyConstraint('id_ejerciciosxbloque'),
    sa.UniqueConstraint('id_ejerciciosxbloque')
    )
    op.drop_table('exercises', schema='lacucha')
    op.drop_table('blocks', schema='lacucha')
    op.drop_table('sessions', schema='lacucha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id_exercise', sa.INTEGER(), server_default=sa.text("nextval('lacucha.exercises_id_exercise_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_exercise', name='exercises_pkey'),
    sa.UniqueConstraint('id_exercise', name='exercises_id_exercise_key'),
    schema='lacucha'
    )
    op.create_table('blocks',
    sa.Column('id_block', sa.INTEGER(), server_default=sa.text("nextval('lacucha.blocks_id_block_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('block_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_session', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_session'], ['lacucha.sessions.id_session'], name='blocks_id_session_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_block', name='blocks_pkey'),
    sa.UniqueConstraint('id_block', name='blocks_id_block_key'),
    schema='lacucha'
    )
    op.create_table('sessions',
    sa.Column('id_session', sa.INTEGER(), server_default=sa.text("nextval('lacucha.sessions_id_session_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_session', name='sessions_pkey'),
    sa.UniqueConstraint('id_session', name='sessions_id_session_key'),
    schema='lacucha'
    )
    op.drop_table('ejerciciosxbloque')
    op.drop_table('bloques')
    op.drop_table('sesiones')
    op.drop_table('mesociclos')
    op.drop_table('usuarios')
    op.drop_table('ejercicios')
    op.drop_table('patrones_movimiento')
    op.drop_table('organizaciones')
    op.drop_table('objetivos')
    op.drop_table('niveles')
    op.drop_table('generos')
    op.drop_table('estados_mesociclo')
    # ### end Alembic commands ###
