"""empty message

Revision ID: 2021c1969b59
Revises: dd17e5fbe2a2
Create Date: 2020-06-29 22:07:50.509905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2021c1969b59'
down_revision = 'dd17e5fbe2a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bloques', ['id_bloques'])
    op.add_column('ejercicios', sa.Column('id_patron', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'ejercicios', ['id_ejercicio'])
    op.create_foreign_key(None, 'ejercicios', 'patrones_movimiento', ['id_patron'], ['id_patron_movimiento'])
    op.drop_column('ejercicios', 'zona')
    op.create_unique_constraint(None, 'ejerciciosxbloque', ['id_ejerciciosxbloque'])
    op.create_unique_constraint(None, 'patrones_movimiento', ['id_patron_movimiento'])
    op.create_unique_constraint(None, 'sesiones', ['id_sesiones'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sesiones', type_='unique')
    op.drop_constraint(None, 'patrones_movimiento', type_='unique')
    op.drop_constraint(None, 'ejerciciosxbloque', type_='unique')
    op.add_column('ejercicios', sa.Column('zona', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ejercicios', type_='foreignkey')
    op.drop_constraint(None, 'ejercicios', type_='unique')
    op.drop_column('ejercicios', 'id_patron')
    op.drop_constraint(None, 'bloques', type_='unique')
    # ### end Alembic commands ###
