"""empty message

Revision ID: 254cb2cbc828
Revises: 2faf281a7b32
Create Date: 2020-05-24 21:13:00.711306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254cb2cbc828'
down_revision = '2faf281a7b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('sessionid', sa.Integer(), nullable=False), schema='lacucha')
    op.create_foreign_key(None, 'blocks', 'sessions', ['sessionid'], ['id_session'], source_schema='lacucha', referent_schema='lacucha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blocks', schema='lacucha', type_='foreignkey')
    op.drop_column('blocks', 'sessionid', schema='lacucha')
    # ### end Alembic commands ###
