"""empty message

Revision ID: 2bc5c3110027
Revises: 77862cff5ff3
Create Date: 2021-01-16 23:59:27.565817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bc5c3110027'
down_revision = '77862cff5ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'estados_mesociclo', ['id_estado_mesociclo'])
    op.add_column('usuarios', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'uuid')
    op.drop_constraint(None, 'estados_mesociclo', type_='unique')
    # ### end Alembic commands ###
