"""empty message

Revision ID: 2faf281a7b32
Revises: 510938e7c7a9
Create Date: 2020-05-24 20:58:20.518848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2faf281a7b32'
down_revision = '510938e7c7a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('sets', sa.Integer(), nullable=True), schema='lacucha')
    op.drop_column('blocks', 'repetitions', schema='lacucha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('repetitions', sa.INTEGER(), autoincrement=False, nullable=True), schema='lacucha')
    op.drop_column('blocks', 'sets', schema='lacucha')
    # ### end Alembic commands ###
