"""empty message

Revision ID: 36916c090daf
Revises: 209e3aba0bc7
Create Date: 2021-05-04 02:33:44.605875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36916c090daf'
down_revision = '209e3aba0bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('baja_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'baja_en')
    # ### end Alembic commands ###
