"""empty message

Revision ID: 376d0be6d9d6
Revises: 4a585c1eafa5
Create Date: 2020-05-24 20:47:19.725970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376d0be6d9d6'
down_revision = '4a585c1eafa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercisesxblock',
    sa.Column('id_exercise', sa.Integer(), nullable=False),
    sa.Column('id_block', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_block'], ['lacucha.blocks.id_block'], ),
    sa.ForeignKeyConstraint(['id_exercise'], ['lacucha.exercises.id_exercise'], ),
    sa.PrimaryKeyConstraint('id_exercise', 'id_block'),
    schema='lacucha'
    )
    op.create_unique_constraint(None, 'blocks', ['id_block'], schema='lacucha')
    op.create_unique_constraint(None, 'exercises', ['id_exercise'], schema='lacucha')
    op.create_unique_constraint(None, 'sessions', ['id_session'], schema='lacucha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', schema='lacucha', type_='unique')
    op.drop_constraint(None, 'exercises', schema='lacucha', type_='unique')
    op.drop_constraint(None, 'blocks', schema='lacucha', type_='unique')
    op.drop_table('exercisesxblock', schema='lacucha')
    # ### end Alembic commands ###
