"""empty message

Revision ID: 48f44c2d3a1b
Revises: 
Create Date: 2021-01-25 21:38:04.208276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f44c2d3a1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejercicios', sa.Column('url_video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ejercicios', 'url_video')
    # ### end Alembic commands ###
