"""empty message

Revision ID: 4a585c1eafa5
Revises: 
Create Date: 2020-05-24 17:31:15.935305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a585c1eafa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id_block', sa.Integer(), nullable=False),
    sa.Column('block_num', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_block'),
    sa.UniqueConstraint('id_block'),
    schema='lacucha'
    )
    op.create_table('exercises',
    sa.Column('id_exercise', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_exercise'),
    sa.UniqueConstraint('id_exercise'),
    schema='lacucha'
    )
    op.create_table('sessions',
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_session'),
    sa.UniqueConstraint('id_session'),
    schema='lacucha'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions', schema='lacucha')
    op.drop_table('exercises', schema='lacucha')
    op.drop_table('blocks', schema='lacucha')
    # ### end Alembic commands ###
