"""empty message

Revision ID: 510938e7c7a9
Revises: 376d0be6d9d6
Create Date: 2020-05-24 20:56:16.468832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510938e7c7a9'
down_revision = '376d0be6d9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('repetitions', sa.Integer(), nullable=True), schema='lacucha')
    op.add_column('exercisesxblock', sa.Column('repetitions', sa.Integer(), nullable=True), schema='lacucha')
    op.add_column('exercisesxblock', sa.Column('weight', sa.Float(), nullable=True), schema='lacucha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercisesxblock', 'weight', schema='lacucha')
    op.drop_column('exercisesxblock', 'repetitions', schema='lacucha')
    op.drop_column('blocks', 'repetitions', schema='lacucha')
    # ### end Alembic commands ###
