"""empty message

Revision ID: 6186c02d389d
Revises: 2bc5c3110027
Create Date: 2021-01-17 00:05:54.631854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6186c02d389d'
down_revision = '2bc5c3110027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('uuid', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'uuid')
    # ### end Alembic commands ###
