"""empty message

Revision ID: 77862cff5ff3
Revises: 
Create Date: 2020-11-03 23:47:02.708481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77862cff5ff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bloques', 'actualizdo_en',
                    new_column_name='actualizado_en')
    op.create_unique_constraint(None, 'bloques', ['id_bloque'])
    op.create_unique_constraint(None, 'ejercicios', ['id_ejercicio'])
    op.create_unique_constraint(None, 'ejerciciosxbloque', [
                                'id_ejerciciosxbloque'])
    op.alter_column('estados_mesociclo', 'id_estados_mesociclo',
                    new_column_name='id_estado_mesociclo')

    op.create_unique_constraint(None, 'generos', ['id_genero'])
    op.create_unique_constraint(None, 'mesociclos', ['id_mesociclo'])
    op.drop_constraint('mesociclos_id_estado_fkey',
                       'mesociclos', type_='foreignkey')
    op.create_foreign_key(None, 'mesociclos', 'estados_mesociclo', [
                          'id_estado'], ['id_estado_mesociclo'])
    op.create_unique_constraint(None, 'niveles', ['id_nivel'])
    op.create_unique_constraint(None, 'objetivos', ['id_objetivo'])
    op.create_unique_constraint(None, 'organizaciones', ['id_organizacion'])
    op.create_unique_constraint(None, 'patrones_movimiento', [
                                'id_patron_movimiento'])
    op.create_unique_constraint(None, 'sesiones', ['id_sesion'])
    op.create_unique_constraint(None, 'usuarios', ['id_usuario'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_constraint(None, 'sesiones', type_='unique')
    op.drop_constraint(None, 'patrones_movimiento', type_='unique')
    op.drop_constraint(None, 'organizaciones', type_='unique')
    op.drop_constraint(None, 'objetivos', type_='unique')
    op.drop_constraint(None, 'niveles', type_='unique')
    op.drop_constraint(None, 'mesociclos', type_='foreignkey')
    op.create_foreign_key('mesociclos_id_estado_fkey', 'mesociclos', 'estados_mesociclo', [
                          'id_estado'], ['id_estados_mesociclo'])
    op.drop_constraint(None, 'mesociclos', type_='unique')
    op.drop_constraint(None, 'generos', type_='unique')
    op.add_column('estados_mesociclo', sa.Column(
        'id_estados_mesociclo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'estados_mesociclo', type_='unique')
    op.drop_column('estados_mesociclo', 'id_estado_mesociclo')
    op.drop_constraint(None, 'ejerciciosxbloque', type_='unique')
    op.drop_constraint(None, 'ejercicios', type_='unique')
    op.add_column('bloques', sa.Column('actualizdo_en',
                                       postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bloques', type_='unique')
    op.drop_column('bloques', 'actualizado_en')
    # ### end Alembic commands ###
