"""empty message

Revision ID: b33949d4fb8b
Revises: 377b296b5ebb
Create Date: 2020-06-02 11:28:38.837661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33949d4fb8b'
down_revision = '377b296b5ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('id_session', sa.Integer(), nullable=False), schema='lacucha')
    op.drop_constraint('blocks_sessionid_fkey', 'blocks', schema='lacucha', type_='foreignkey')
    op.create_foreign_key(None, 'blocks', 'sessions', ['id_session'], ['id_session'], source_schema='lacucha', referent_schema='lacucha')
    op.drop_column('blocks', 'sessionid', schema='lacucha')
    op.add_column('exercisesxblock', sa.Column('id_block', sa.Integer(), nullable=True), schema='lacucha')
    op.add_column('exercisesxblock', sa.Column('id_exercise', sa.Integer(), nullable=True), schema='lacucha')
    op.drop_constraint('exercisesxblock_exercise_id_fkey', 'exercisesxblock', schema='lacucha', type_='foreignkey')
    op.drop_constraint('exercisesxblock_block_id_fkey', 'exercisesxblock', schema='lacucha', type_='foreignkey')
    op.create_foreign_key(None, 'exercisesxblock', 'exercises', ['id_exercise'], ['id_exercise'], source_schema='lacucha', referent_schema='lacucha')
    op.create_foreign_key(None, 'exercisesxblock', 'blocks', ['id_block'], ['id_block'], source_schema='lacucha', referent_schema='lacucha')
    op.drop_column('exercisesxblock', 'exercise_id', schema='lacucha')
    op.drop_column('exercisesxblock', 'block_id', schema='lacucha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercisesxblock', sa.Column('block_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='lacucha')
    op.add_column('exercisesxblock', sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='lacucha')
    op.drop_constraint(None, 'exercisesxblock', schema='lacucha', type_='foreignkey')
    op.drop_constraint(None, 'exercisesxblock', schema='lacucha', type_='foreignkey')
    op.create_foreign_key('exercisesxblock_block_id_fkey', 'exercisesxblock', 'blocks', ['block_id'], ['id_block'], source_schema='lacucha', referent_schema='lacucha')
    op.create_foreign_key('exercisesxblock_exercise_id_fkey', 'exercisesxblock', 'exercises', ['exercise_id'], ['id_exercise'], source_schema='lacucha', referent_schema='lacucha')
    op.drop_column('exercisesxblock', 'id_exercise', schema='lacucha')
    op.drop_column('exercisesxblock', 'id_block', schema='lacucha')
    op.add_column('blocks', sa.Column('sessionid', sa.INTEGER(), autoincrement=False, nullable=False), schema='lacucha')
    op.drop_constraint(None, 'blocks', schema='lacucha', type_='foreignkey')
    op.create_foreign_key('blocks_sessionid_fkey', 'blocks', 'sessions', ['sessionid'], ['id_session'], source_schema='lacucha', referent_schema='lacucha')
    op.drop_column('blocks', 'id_session', schema='lacucha')
    # ### end Alembic commands ###
