"""empty message

Revision ID: dd17e5fbe2a2
Revises: 
Create Date: 2020-06-24 00:00:37.087661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd17e5fbe2a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicios',
    sa.Column('id_ejercicio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('zona', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_ejercicio'),
    sa.UniqueConstraint('id_ejercicio')
    )
    op.create_table('sesiones',
    sa.Column('id_sesiones', sa.Integer(), nullable=False),
    sa.Column('fecha_empezado', sa.DateTime(), nullable=True),
    sa.Column('fecha_finalizado', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_sesiones'),
    sa.UniqueConstraint('id_sesiones')
    )
    op.create_table('bloques',
    sa.Column('id_bloques', sa.Integer(), nullable=False),
    sa.Column('id_sesiones', sa.Integer(), nullable=False),
    sa.Column('num_bloque', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizdo_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sesiones'], ['sesiones.id_sesiones'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id_bloques'),
    sa.UniqueConstraint('id_bloques')
    )
    op.create_table('ejerciciosxbloque',
    sa.Column('id_ejerciciosxbloque', sa.Integer(), nullable=False),
    sa.Column('id_ejercicio', sa.Integer(), nullable=True),
    sa.Column('id_bloque', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('carga', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_bloque'], ['bloques.id_bloques'], ),
    sa.ForeignKeyConstraint(['id_ejercicio'], ['ejercicios.id_ejercicio'], ),
    sa.PrimaryKeyConstraint('id_ejerciciosxbloque'),
    sa.UniqueConstraint('id_ejerciciosxbloque')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ejerciciosxbloque')
    op.drop_table('bloques')
    op.drop_table('sesiones')
    op.drop_table('ejercicios')
    # ### end Alembic commands ###
