"""empty message

Revision ID: e70c45517212
Revises: eb597c430e39
Create Date: 2021-06-28 20:47:40.894560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70c45517212'
down_revision = 'eb597c430e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas',
    sa.Column('id_plantilla', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('id_nivel', sa.Integer(), nullable=True),
    sa.Column('id_objetivo', sa.Integer(), nullable=True),
    sa.Column('id_organizacion', sa.Integer(), nullable=True),
    sa.Column('sesiones_por_semana', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_nivel'], ['niveles.id_nivel'], ),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivos.id_objetivo'], ),
    sa.ForeignKeyConstraint(['id_organizacion'], ['organizaciones.id_organizacion'], ),
    sa.PrimaryKeyConstraint('id_plantilla'),
    sa.UniqueConstraint('id_plantilla'),
    sa.UniqueConstraint('id_plantilla')
    )
    op.create_table('sesionesxplantilla',
    sa.Column('id_sesionesxplantilla', sa.Integer(), nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=True),
    sa.Column('id_plantilla', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plantilla'], ['plantillas.id_plantilla'], ),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesiones.id_sesion'], ),
    sa.PrimaryKeyConstraint('id_sesionesxplantilla'),
    sa.UniqueConstraint('id_sesionesxplantilla'),
    sa.UniqueConstraint('id_sesionesxplantilla')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesionesxplantilla')
    op.drop_table('plantillas')
    # ### end Alembic commands ###
