"""empty message

Revision ID: eb597c430e39
Revises: 2bf96307edc3
Create Date: 2021-06-06 21:50:41.495304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb597c430e39'
down_revision = '2bf96307edc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejercicios', sa.Column('peso_inicial', sa.Integer(), nullable=True))
    op.add_column('ejercicios', sa.Column('es_temporal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ejercicios', 'es_temporal')
    op.drop_column('ejercicios', 'peso_inicial')
    # ### end Alembic commands ###
