"""empty message

Revision ID: 2bf96307edc3
Revises: 
Create Date: 2021-06-01 20:45:25.028952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf96307edc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejerciciosxbloque', sa.Column('num_ejercicio', sa.Integer(), nullable=True))
    op.add_column('sesiones', sa.Column('num_sesion', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('rol', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('baja_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'baja_en')
    op.drop_column('usuarios', 'rol')
    op.drop_column('sesiones', 'num_sesion')
    op.drop_column('ejerciciosxbloque', 'num_ejercicio')
    # ### end Alembic commands ###
